name: CoreyBlake
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64657
title: Corey Blake Creative
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#363537'
    - '#000000'
    - '#fac032'
    - '#d6d6d6'
    - '#737273'
  brandStrength: 0.875
  lightness: 0.743461309466511
  saturation: 0.38310804357752204
  rhythmicContrast: 0.6377619032282382
purpose: []
